export const bettingData = [
  {
    id: 1,
    description: "will delete production DB",
    creator: "User 1",
    target: "User 2",
    duration: "2d",
    optionA: { points: 500, percentage: 10 },
    optionB: { points: -100, percentage: 90 },
  },
  {
    id: 2,
    description: "will wear a clown suit to the meeting",
    creator: "User 5",
    target: "User 2",
    duration: "1d",
    optionA: { points: 200, percentage: 30 },
    optionB: { points: -50, percentage: 70 },
  },
  {
    id: 3,
    description: "will push to main without review",
    creator: "User 9",
    target: "User 1",
    duration: "4h",
    optionA: { points: 150, percentage: 40 },
    optionB: { points: -150, percentage: 60 },
  },
  {
    id: 4,
    description: "will fix the bug on first try",
    creator: "User 3",
    target: "User 80",
    duration: "6h",
    optionA: { points: 1000, percentage: 5 },
    optionB: { points: -50, percentage: 95 },
  },
  {
    id: 5,
    description: "will survive the spicy noodle challenge",
    creator: "User 4",
    target: "User 2",
    duration: "3d",
    optionA: { points: 300, percentage: 50 },
    optionB: { points: -300, percentage: 50 },
  },
  {
    id: 6,
    description: "will accidentally reply all",
    creator: "User 6",
    target: "User 60",
    duration: "1w",
    optionA: { points: 100, percentage: 25 },
    optionB: { points: -25, percentage: 75 },
  },
  {
    id: 7,
    description: "will find the missing semicolon in < 1 hour",
    creator: "User 7",
    target: "User 85",
    duration: "1h",
    optionA: { points: 50, percentage: 60 },
    optionB: { points: -50, percentage: 40 },
  },
  {
    id: 8,
    description: "will win the hackathon",
    creator: "User 8",
    target: "User 96",
    duration: "2d",
    optionA: { points: 5000, percentage: 1 },
    optionB: { points: -100, percentage: 99 },
  },
  {
    id: 9,
    description: "will sleep through the standup",
    creator: "User 9",
    target: "User 64",
    duration: "12h",
    optionA: { points: 80, percentage: 15 },
    optionB: { points: -20, percentage: 85 },
  },
  {
    id: 10,
    description: "will use light mode for a whole day",
    creator: "User 10",
    target: "User 67",
    duration: "1d",
    optionA: { points: 600, percentage: 5 },
    optionB: { points: -50, percentage: 95 },
  },
  {
    id: 11,
    description: "will get coffee spilled on them",
    creator: "User 11",
    target: "User 68",
    duration: "3d",
    optionA: { points: 120, percentage: 20 },
    optionB: { points: -30, percentage: 80 },
  },
  {
    id: 12,
    description: "will mention 'AI' in the next 5 mins",
    creator: "User 12",
    target: "User 69",
    duration: "5m",
    optionA: { points: 40, percentage: 80 },
    optionB: { points: -160, percentage: 20 },
  },
  {
    id: 13,
    description: "will break the build",
    creator: "User 45",
    target: "User 36",
    duration: "1d",
    optionA: { points: 200, percentage: 35 },
    optionB: { points: -100, percentage: 65 },
  },
  {
    id: 14,
    description: "will eat lunch at their desk",
    creator: "User 46",
    target: "User 71",
    duration: "4h",
    optionA: { points: 20, percentage: 90 },
    optionB: { points: -180, percentage: 10 },
  },
  {
    id: 15,
    description: "will say 'It works on my machine'",
    creator: "User 47",
    target: "User 54",
    duration: "2d",
    optionA: { points: 50, percentage: 70 },
    optionB: { points: -100, percentage: 30 },
  },
  {
    id: 16,
    description: "will forget to unmute",
    creator: "User 48",
    target: "User 55",
    duration: "1h",
    optionA: { points: 30, percentage: 60 },
    optionB: { points: -45, percentage: 40 },
  },
  {
    id: 17,
    description: "will deploy on Friday",
    creator: "User 49",
    target: "User 32",
    duration: "5d",
    optionA: { points: 1000, percentage: 10 },
    optionB: { points: -100, percentage: 90 },
  },
  {
    id: 18,
    description: "will use Vim",
    creator: "User 50",
    target: "User 56",
    duration: "1w",
    optionA: { points: 400, percentage: 15 },
    optionB: { points: -60, percentage: 85 },
  },
  {
    id: 19,
    description: "will ask a question already answered in docs",
    creator: "User 51",
    target: "User 51",
    duration: "1d",
    optionA: { points: 60, percentage: 55 },
    optionB: { points: -70, percentage: 45 },
  },
  {
    id: 20,
    description: "will become a meme",
    creator: "User 30",
    target: "User 90",
    duration: "1mo",
    optionA: { points: 2000, percentage: 2 },
    optionB: { points: -50, percentage: 98 },
  },
];
